# Global chart configuration
#global:
  # App name
  #app:

  # Deployment environment
  #env:

  #namespace:

# Prometheus configuration
prometheus:
  # Number of duplicate prometheus instances
  replicas: 3

# Alert manager configuration
alertmanager:
  # Number of replicas in alertmanager highly available cluster
  replicas: 3

  # Specifies if alerts should be setup
  alertsEnabled: True

# Grafana configuration
grafana:
  # Number of duplicate grafana instances
  replicas: 3

  # Name of organization which all users will be part of
  organization: KScout

  # Container port to run server on
  containerPort: 3000

# scrapePortsRegex matches ports which should be scanned on pods
scrapePortsRegex: 9180|9090

# Services to monitor
services:
  #  Name of service without environment prefix or component postfix
  #  Should match the expression /[0-9a-zA-Z-_]+/
  #- name:
  #  Space separated list of maintainer Slack handles
  #  Will be pinged if an alert is triggered for this service
  #  slack_maintainers:
  #  External network traffic host
  #  host:
  - name: serverless-registry-api
    slack_maintainers: '@nhuppert @pmahajan'
    host: api.kscout.io
  - name: site
    slack_maintainers: '@jawalter'
    host: kscout.io
  - name: chat-bot-api
    slack_maintainers: '@vhire @pmahajan'
    host: bot.kscout.io
  - name: slack-chat-bot-api
    slack_maintainers: '@vhire @pmahajan'
    host: slack-bot.kscout.io
