# Global chart configuration
#global:
  # App name
  #app:

  # Deployment environment
  #env:

# Prometheus configuration
prometheus:
  # Number of duplicate prometheus instances
  replicas: 3

# Alert manager configuration
alertmanager:
  # Number of replicas in alertmanager highly available cluster
  replicas: 3

  # Specifies if alerts should be setup
  alertsEnabled: True

# Services to monitor
services:
  #  Name of service without environment prefix or component postfix
  #- name:
  #  Space separated list of maintainer Slack handles
  #  Will be pinged if an alert is triggered for this service
  #  slack_maintainers:
  - name: serverless-registry-api
    slack_maintainers: '@nhuppert @pmahajan'
  - name: site
    slack_maintainers: '@jawalter'
  - name: chat-bot-api
    slack_maintainers: '@vhire @pmahajan'
  - name: slack-chat-bot-api
    slack_maintainers: '@vhire @pmahajan'
