{{/*
Template evaluated with root context.
*/}}
groups:
{{ range .Values.services }}
{{ $_ := dict "env" $.Values.global.env "name" .name }}
  # Alert when external ping for {{ .name }} fails
  - name: {{ .name }}
    rules:
      - alert: {{ template "cluster-observability.title-name" . }} ping failed
        expr: probe_success{job="blackbox-exporter",app="{{ .name }}"} < 1
        for: 3m
        labels:
          app: {{ .name }}
          maintainers: '{{ .slack_maintainers }}'
          severity: critical
          host: {{ .host }}
        annotations:
          title: Failed to ping {{ template "cluster-observability.title-name" . }}
          description: The blackbox exporter failed to ping the {{ template "cluster-observability.title-name" . }} for at least 1 minute.
{{ end }}
