{{/*
Template evaluated with root context.
*/}}
groups:
  - name: all-targets
    rules:
      - alert: Metrics target down
        expr: up < 1
        for: 1m
        labels:
          severity: critical
        annotations:
          title: Metrics target down
          description: A target which is scraped for metrics has not been reachable for at least 1 minute.
{{ range .Values.services }}
{{ $_ := dict "env" $.Values.global.env "name" .name }}
  - name: {{ .name }}
    rules:
      - alert: {{ template "cluster-observability.title-name" . }} ping failed
        expr: probe_success{job="blackbox-exporter",app="{{ .name }}"} < 1
        for: 1m
        labels:
          app: {{ .name }}
          maintainers: '{{ .slack_maintainers }}'
          severity: critical
          host: {{ .host }}
        annotations:
          title: Failed to ping {{ template "cluster-observability.title-name" . }}
          description: The blackbox exporter failed to ping the {{ template "cluster-observability.title-name" . }} for at least 1 minute.
{{ end }}
