modules:
  https_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      fail_if_not_ssl: True
      tls_config:
        insecure_skip_verify: False
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
