apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data
  labels:
    app: {{ .Values.global.app }}
    component: alertmanager
    env: {{ .Values.global.app }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
