apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.global.env }}-alertmanager
  labels:
    app: {{ .Values.global.app }}
    component: alertmanager
    env: {{ .Values.global.env }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.app }}
      component: alertmanager
      env: {{ .Values.global.env }}
  serviceName: {{ .Values.global.app }}-alertmanager
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.global.app }}
        component: alertmanager
        env: {{ .Values.global.env }}
      annotations:
        {{- range $path, $_ := .Files.Glob "config/alertmanager/*" }}
        config-{{ $path | base }}-sha256sum: {{ tpl ($.Files.Get $path) $ | sha256sum }}
        {{- end }}
    spec:
      volumes:
        - name: alertmanager-config
          configMap:
            name: {{ .Values.global.env }}-alertmanager-config
      containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:latest
          volumeMounts:
            - name: alertmanager-config
              mountPath: /mnt/config
          args:
            - "--config.file=/mnt/config/alertmanager.yml"
            - "--storage.path=/tmp/alertmanager"
            {{- range $i, $v := until (.Values.alertmanager.replicas | int) }}
            - "--cluster.peer={{ $.Values.global.env }}-alertmanager-{{ $i }}:9093"
            {{- end }}
          ports:
            - name: web
              containerPort: 9093
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
