apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: observability
    component: alertmanager
    env: prod
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    nodePort: 30930
    protocol: TCP
    targetPort: web
  selector:
    app: observability
    component: alertmanager
    env: prod
