apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data
  labels:
    app: observability
    component: alertmanager
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
