apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-alertmanager
  labels:
    app: {{ .Values.global.app }}
    component: alertmanager
    env: {{ .Values.global.env }}
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  - name: discovery
    port: 6783
    protocol: TCP
    targetPort: discovery
  selector:
    app: {{ .Values.global.app }}
    component: alertmanager
    env: {{ .Values.global.env }}
