apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-blackbox-exporter
  labels:
    app: {{ .Values.global.app }}
    component: blackbox-exporter
    env: {{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.global.app }}
    component: blackbox-exporter
    env: {{ .Values.global.env }}
  ports:
    - name: metrics
      targetPort: metrics
      protocol: TCP
      port: 9115
