apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.env }}-prometheus-service-account
  labels:
    app: {{ .Values.global.app }}
    component: prometheus
    env: {{ .Values.global.env }}
