apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.env }}-prometheus-role-binding
  labels:
    app: {{ .Values.global.app }}
    component: prometheus
    env: {{ .Values.global.env }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.env }}-prometheus-service-account
roleRef:
  kind: Role
  name: {{ .Values.global.env }}-prometheus-role
  apiGroup: rbac.authorization.k8s.io
