apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: observability
    component: prometheus
    env: prod
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    nodePort: 30900
    protocol: TCP
    targetPort: web
  selector:
    app: observability
    component: prometheus
    env: prod
