apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: {{ .Values.global.app }}
    component: prometheus
    env: {{ .Values.global.app }}
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    nodePort: 30900
    protocol: TCP
    targetPort: web
  selector:
    app: {{ .Values.global.app }}
    component: prometheus
    env: {{ .Values.global.app }}
