apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: prometheus
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: prometheus
      env: prod
  template:
    metadata:
      labels:
        app: prometheus
        component: prometheus
        env: prod
    spec:
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:latest
          volumeMounts:
            - name: prometheus-config
              mountPath: /mnt/config
            - name: prometheus-data
              mountPath: /mnt/data
          args:
            - "--config.file=/mnt/config/prometheus.yml"
            - "--storage.tsdb.path=/mnt/data"
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
