apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: {{ .Values.global.app }}
    component: prometheus
    env: {{ .Values.global.env }}
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
           - alertmanager:9093
           
    rule_files:
      - "/mnt/config/alert_rules.yml"
      
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090'] # Prometheus self metrics

      - job_name: 'services'
        static_configs:
        - targets:
            - 'prod-serverless-registry-api-metrics:9180' # Serverless registry API
            - 'prod-site-metrics:9180' # Site
  alert_rules.yml: |
    groups:
      - name: serverless-registry-api
        rules:
          - alert: Serverless Registry API Down
            expr: up{instance="prod-serverless-registry-api-metrics:9180"} < 1
            for: 1m
            labels:
              severity: high
              maintainers: '@nhuppert @pmahajan'
            annotations:
              summary: Serverless Registry API Down
              description: No metrics received from the Serverless Registry API proxy for at least 1 minute.
      - name: site
        rules:
          - alert: Site Down
            expr: up{instance="prod-site-metrics:9180"} < 1
            for: 1m
            labels:
              severity: high
              maintainers: '@jawalter'
            annotations:
              summary: Site Down
              description: No metrics received from the site proxy for at least 1 minute.
